_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/ai_train.py
        m:
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_step
              "6": []
              "7": []
            - "1": eval_accuracy
              "5": 4
              "6":
                - 1
                - 3
              "7": []
            - "1": eval_step
              "6": []
              "7": []
        python_version: 3.9.7
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 7
                - 23
                - 55
                - 67
            "4": 3.9.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
